spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
mybatis:
  config-location : classpath:mybatis-config.xml